// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace IOApp.CompiledModels
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var fileEntity = FileEntityEntityType.Create(this);

            FileEntityEntityType.CreateAnnotations(fileEntity);

            AddAnnotation("ProductVersion", "7.0.14");
        }
    }
}
